import { env } from '@/env.mjs';

export const siteConfig = {
  title:
    'Umar | Front-End Engineer | MERN/MEVN Stack Dev | Full Stack Web Developer | React-Native Developer',
  description:
    'Hi there! My name is Umar and I am a programmer with a passion for learning and exploring new technologies. With a strong background in full-stack development, I have a well-rounded skill set and am always looking to expand my knowledge and take on new challenges. As a dedicated and driven individual, I am constantly seeking out opportunities to grow and improve as a programmer.',
  keywords: [
    'Umar projects',
    'Projects by Mohammad Umar',
    'Mohammad Umar',
    'Contact Mohammad Umar',
    'Projects of Mohammad Umar',
    'Best Freelancer Near me',
    'Affordable Freelancer Near me',
    'Hourly based paid freelancer near me',
    'React-Native Developer near me',
    'React.js Developer Near me',
    'Next.js Developer Near me',
    'Best Freelancer',
    'Front-End Engineer',
    'MERN/MEVN Stack Dev',
    'Full Stack Web Developer',
    'Front-end React-Native Developer',
    'Freelance web development',
    'React-Native development services',
    'MERN Stack projects',
    'MEVN Stack development',
    'Web development portfolio',
    'Mohammad Umar portfolio',
    'Freelancer services',
    'Full Stack Developer',
    'Who is Mohammad Umar?',
    'Where does Mohammad Umar Live?',
    'Web Developer Near me',
    'Front-End Developer near me',
    'Domain Name purchase',
    'Top-rated freelancer',
    'Expert web developer',
    'Skilled React-Native Developer',
    'Professional MERN/MEVN Stack Developer',
    'Exceptional Full Stack Web Developer',
    'Local freelance talent',
    'Outstanding Front-End Engineer',
    'Best web development services',
    'Reliable freelance developer',
    'Talented React-Native specialist',
    'TypeScript Developer',
    'JavaScript Developer',
    'UI/UX Design',
    'Responsive Design',
    'Remote Developer',
    'Portfolio',
    'Website Development',
    'Web Applications',
    'Tailwind CSS',
    'MongoDB',
    'Express.js',
    'Vue.js',
    'GitHub',
    'Vercel',
    'Netlify',
    'United Kingdom',
    'Available for Hire',
    'Open Source Contributor',
  ],
  url: env.SITE_URL || 'https://yash-kapure.vercel.app',
  googleSiteVerificationId:
    env.GOOGLE_SITE_VERIFICATION_ID ||
    'zjseZ18pLQ6Tg4nvpJJkRVevf7dK4QzbpzMuZNCKNYQ',
};
